title: RJ Dasein
url: https://rjdasein.com

owner:
  name: Ruijie Wu
  avatar: comimagesavatar.jpg.png
  email: hello@rjdasein.com
  linkedin: eaglepsy
  scholar:
  researchgate:

google_verify: ""

links:
  - title: About
    url: /

  - title: Services
    url: /services/

  - title: Workshops
    url: /workshops/

  - title: Writing
    url: /writing/

  - title: Contact
    url: /contact/

timezone: Asia/Ho_Chi_Minh
future: true
highlighter: rouge

permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
